In [12]:
import numpy as np

In [8]:
a = np.array([1,2,3]) #arra só permite elementos do mesmo tipo

In [9]:
print(a)

[1 2 3]


In [16]:
# estrutura de matriz 
b = np.array([(1,2,3),(4,5,6)])

In [14]:
print(b)

[[1 2 3]
 [4 5 6]]


In [21]:
#função numpy para criar matriz de zeros e um's

c = np.zeros((2,2)) #dimensionando matriz de zeros
d = np.ones((3,3))

In [22]:
print(c)
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
#função numpy para criar matriz identidade NxN

e = np.eye(6) #dimensionando N

print(e)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [28]:
#funções matemáticas interessantes do numpy

print(np.max(b)) #elemento máximo
print(np.min(b)) #elemento mínimo
print(np.sum(b)) #soma dos elementos
print(np.mean(b)) #média dos elementos
print(np.std(b)) #desvio padrão dos elementos



6
1
21
3.5
1.707825127659933
