In [2]:
import pandas as pd
alunos = {'Nome': ['Fabio', 'Ana', 'Rob', 'Karim'],
        'Nota': [1, 2, 3, 4.5],
        'Situação': ['Sim', 'Sim', 'Não', 'Sim']} #dicionário

In [3]:
#função dataframe recebendo um dicionário
dataframe = pd.DataFrame(alunos)

In [4]:
print(dataframe)

    Nome  Nota Situação
0  Fabio   1.0      Sim
1    Ana   2.0      Sim
2    Rob   3.0      Não
3  Karim   4.5      Sim


In [5]:
#função série do pandas do tipo 1-dimensional
objeto1 = pd.Series([10, 9, 8, 7, 6])
print(objeto1)

0    10
1     9
2     8
3     7
4     6
dtype: int64


In [9]:
import numpy as np
array = np.array([(10, 9, 8, 7, 6), (1, 2, 3, 4, 5)])
array2 = np.array([10, 9, 8, 7, 6])
print(array)
print(array2)

[[10  9  8  7  6]
 [ 1  2  3  4  5]]
[10  9  8  7  6]


In [13]:
#função séries não pode transformar elementos que não sejam 1-dimensionais
objeto2 = pd.Series(array2)
print(objeto2)

0    10
1     9
2     8
3     7
4     6
dtype: int32
